-- noinspection SqlNoDataSourceInspectionForFile
-- noinspection SqlDialectInspectionForFile

--
-- Schema
--
CREATE TABLE IF NOT EXISTS public.users (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         VARCHAR(255) DEFAULT NULL unique,
  apple_id      VARCHAR(255) DEFAULT NULL,
  google_id     VARCHAR(255) DEFAULT NULL,
  facebook_id   VARCHAR(255) DEFAULT NULL,
  created_at    TIMESTAMP with TIME ZONE DEFAULT timezone('utc' :: text, now()) NOT NULL
);
