version: '3.4'

services:
  php:
    build:
      context: .
      target: app_php
    container_name: ${PROJECT_NAME:-playground}-php
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - php_socket:/var/run/php
    environment:
      DATABASE_URL: pgsql:host=database;port=5432;dbname=${DB_NAME:-playground};user=${DB_USER:-app};password=${DB_PASSWORD:-!ChangeMe!}
      S3_URL: ${S3_URL}
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_ACCESS_SECRET: ${S3_ACCESS_SECRET}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
      APPLE_TEAM_ID: ${APPLE_TEAM_ID}
      APPLE_KEY_ID: ${APPLE_KEY_ID}
      APPLE_SERVICE_ID: ${APPLE_SERVICE_ID}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET}
      FACEBOOK_REDIRECT_URI: ${FACEBOOK_REDIRECT_URI}

  caddy:
    build:
      context: .
      target: app_caddy
    container_name: ${PROJECT_NAME:-playground}-caddy
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    container_name: ${PROJECT_NAME:-playground}-database
    environment:
      POSTGRES_DB: ${DB_NAME:-playground}
      POSTGRES_USER: ${DB_USER:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-!ChangeMe!}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  php_socket:
  caddy_data:
  caddy_config:
  db_data:
